# tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/cask"
tap "buo/cask-upgrade"
tap "homebrew/command-not-found"
brew "mas"

# tap "sambadevi/powerlevel9k"
brew "amazon-ecs-cli", link: false
brew "automake"
brew "xz"
brew "python@3.9"
brew "awscli"
brew "boost"
brew "bzip2"
brew "chamber"
brew "cli53"
brew "coreutils"
brew "openldap"
brew "curl"
brew "docker"
brew "gcc"
brew "gh"
brew "git"
brew "glib"
brew "gnu-tar"
brew "libtool"
brew "pkg-config"
brew "nghttp2"
brew "gnupg"
brew "go"
brew "grep"
brew "hadolint"
brew "highlight"
brew "jq"
brew "node"
brew "jsonlint"
brew "kubernetes-cli"
brew "lima"
brew "mercurial"
brew "neovim"
brew "nvm"
brew "pipenv"
brew "pipx"
brew "postgresql", restart_service: true
brew "postgresql@11", restart_service: true
brew "pre-commit"
brew "pwgen"
brew "pyenv"
brew "serverless"
brew "shellcheck"
brew "starship"
brew "terraform-docs"
brew "tfenv"
brew "tflint"
brew "wget"
brew "zlib"

cask "1password"
cask "authy"
cask "aws-vault"
cask "drawio"
# cask "font-meslo-lg-nerd-font"
cask "font-hack-nerd-font"
cask "font-fira-code-nerd-font"
cask "github"
cask "iterm2"
cask "slack"
cask "visual-studio-code"
